### ISSUE TITLE
'GoogleSignIn/GIDAuthentication.h' file not found

### ISSUE THREAD

**Issue by yashs-devstree** [Thaina/google-signin-unity#22]
Hello @Thaina 

I'm getting this error in iOS build. Even though plugin have that file. This error is there in Unity 2022 LTS and Unity 6 LTS as well. Can you please guide me how can I resolve it?

`/Builds/iOS/Libraries/Plugins/iOS/GoogleSignIn/GoogleSignIn.mm:17:9 'GoogleSignIn/GIDAuthentication.h' file not found`

**Comment by Thaina** [comment]
How you install this plugin and are there any other error in unity build?

I suspect that the build did not have google signin framework in xcode, can you check if google signin was added in xcode? And what if it was added manually?

https://stackoverflow.com/a/58480718/1260333

Or maybe it was because google have update iospod got google signin recently. I don't have macos machine right now so I am very sorry may not be any help because I can't test anything related to ios

**Comment by yashs-devstree** [comment]
I've installed the plugin via git in UPM dependency and no there is no other error. If you want to check I can provide you access to my system or should I specify particular pod version to make it work?

**Comment by Thaina** [comment]
Which branch you using?

**Comment by yashs-devstree** [comment]
I'm using new migration branch

**Comment by Thaina** [comment]
Then let's see what version the google signin was being resolved. Is it 7 or 8

**Comment by yashs-devstree** [comment]
It's 7.1.0
![image](https://github.com/user-attachments/assets/8168e070-ddeb-4807-9140-c2334019bedc)

**Comment by Thaina** [comment]
Then let's check the build phase if it was include bundle and framework properly

![image](https://github.com/user-attachments/assets/5b086e52-588e-41c6-b873-649723a8371d)

**Comment by yashs-devstree** [comment]
So in latest version there is no google utilities. I'm attaching screenshots below.
![image](https://github.com/user-attachments/assets/1045a78b-6866-4640-8dab-1cc78904f02c)
![image](https://github.com/user-attachments/assets/ee4f0007-98f9-426b-97a0-8b25b221a043)

**Comment by Thaina** [comment]
As I have mention, first let's try to add framework manually by + sign

Second. Let's see if the google at the build phase is version 7 or 8. I think it said 7 in plist but it may resolve 8 at the build phase

Maybe you might try to change sign from `~> 7.1.4` to more strict sign so that it will pull 7 to build in the meantime. But I don't remember what symbol to use

Some other fork might also solve this problem. But I can't test it myself right now

**Comment by yashs-devstree** [comment]
So apparently this project is old and I previously used official google sign in repo and added it in unity project itself and not as a UPM dependancy and now since the official plugin not functioning I updated the plugin with your branch using UPM method and I did deleted other folders but forgot to remove the files from plugins folder and due to which I was facing this issue. Removing the files from plugins folder resolved the issue.

**Comment by personatheorygames** [comment]
Hello @Thaina and @yashs-devstree I know this thread has been closed but I'm facing the exact problem like @yashs-devstree except that I imported the files through UPM. In here I will attached a picture showing the problems and what files exist in my project.

1. Google Sign In files through UPM.
2. GoogleSignInDependencies.xml in the project files.
3. This is Podfile generated after I built for IOS.
4. External Dependency Manager.
5. Error that appear.

Notes:
- I'm using Windows to build for IOS.
- Android works perfectly fine and able to do the Google Sign In with the new migration.
- Info.plist not yet downloaded or added from Google Cloud due to struggling to solve this issue for IOS.

I'm really appreciate if I can get any guide to solve this issue. Thanks

![image](https://github.com/user-attachments/assets/7a96e54a-a214-4488-9ca1-a295e1edff6b)
 
![image](https://github.com/user-attachments/assets/c0d709b9-fbe8-44b7-ab89-d822b92fc605)

![image](https://github.com/user-attachments/assets/3f5ffd6d-5759-4611-b397-169e1ba73512)

![image](https://github.com/user-attachments/assets/e462308c-1da3-4151-8c92-87c244e4ef60)

![image](https://github.com/user-attachments/assets/58a5f4fa-402f-4f53-b142-daa046cf9276)
